### ISSUE TITLE
话说这样的话那cxx是不是可以将ue5的代码给到rust呢

### ISSUE THREAD

**Issue by hjyfu** [yeejlan/ue5_rust_demo#1]

**Comment by yeejlan** [comment]
这比较难，现在能做的只是让rust写一些数据库访问，或者http请求接口给UE用。
让rust调用cpp，仅仅把UObject跟常用数据结构传给rust，并不好用。
要想用rust生成UE认识的类，需要把UClass，UProperty这些标签传递给rust，这工作量就太巨大了。
不如直接用现成的，比如UnrealSharp。
